language: c

sudo: required

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap

install:
    - R --version
    - CXX=g++
    - CXXFLAGS="-mtune=native -03 -Wall -pedantic -Wconversion"
    - R CMD config CXX
    - R CMD SHLIB -o hello.so hello.cpp

# If "R --version" fails to compile. 

script: 
    - echo done.

notifications:
    email:
        on_success: change
        on_failure: change