language: c

sudo: required

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - "./travis-tool.sh bootstrap"

install:
    - R --version
    - CXX=g++
    - CXXFLAGS="-mtune=native -03 -Wall -pedantic -Wconversion"
    - R CMD config CXX
    - R CMD SHLIB -o hello.so hello.cpp

script:
    - echo done.

deploy:
  provider: releases
  api_key:
    secure: fLVhN7tYeGOv71waiOeXRaBlY2QX0x5j/d6mQGcIvC/4btUSGH33TbHhmzQwgXQHWQdEYm6mzBdkKbJnXfzwoJSnapweI93JnbnRCZjloE67D85nnw+hcL/+f4dsUgF4gd9ITRNcbBcnygU5rEBVewDF6S+LADbxTCpmDxoOeAcqVrdsNeXfPmujXaf8cYtFbH74mrWDUeOqynNUfMFZA6Jo/WqrDRfyIKWrR3dyphXH1E2wFjXM5KywN+gJ5B/8PItNIC9kM00bSSD84tp6ojupE/3AL7tg0UjJzPGlrnLOX3jfgSZlTXm/tJYNelZEeuDsSH+spW2OlIEwBO7py5lKS/BSWtyw1kEca7Ge5Xq3Fz8sdjeJXU8121gpSu7oP7uSzc7t1R0Vy+yzOrf/QA80OmMZQa6UUlYPg+k3lyaWRSmiaKSQLIg4mX0P3pVlQtEYJSEjYsZdkufyuJoQrqg+Cp7Z4CEmEEMcOYN1lJ+p2t+UXTtspCmtRlyqBtfhFROUf4uZ4T4IcsSS0ZwlPGtRp+MFVHIjiDDuPR5Oiw/NKL8UCSFL8772J9iigsLZgczYWwoXnP5rHO1z/u63IAL5szjcN9XwLmHfmxSntt4IzHXKXaAmzAIpZYi9y3T7B0UitS7JlrUQlQbLa6ydQGQ+vtSQb7LhAYArJ63zh2w=
  file: 
    - ./hello.so
  on:
    tags: true
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change